/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculadora;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Before;

public class AppTest {
    Calculadora c;

    @Before public void setUp() {
        c = new Calculadora();
    }

    @Test public void testSuma() {
        assertTrue(c.suma(2,3)==5);
        assertTrue(c.suma(2.4, 3.2)==5.6);
    }

    @Test public void testMultiplicacion() {
        assertTrue(c.multiplica(4.0,3.0)==12.0);
        assertTrue(c.multiplica(3.1, 2.3)==7.13);
    }
}